site_name: FAR Robotics
nav:
  - Home: index.md

  - Guides:

  - Drivetrain:
    - About: dtr_about.md

    - Installation: dtr_install.md

    - Reporting A Bug: dtr_bugreport.md

    - Docs:
      - Docs Home Page: dtr_docs.md

  - Drivetools:
    - About: dt_about.md

    - Installation: dt_install.md

    - Reporting A Bug: dt_bugreport.md

    - Docs:
      - Docs Home Page: dt_docs.md

      - Displays:
        - Creating Displays: dt_dsp_creating.md
        - Editing Displays: dt_dsp_editing.md
        - Text Display: dt_dsp_text.md
        - Field2D Display: dt_dsp_field2d.md
        - Field3D Display: dt_dsp_field3d.md
        - Button Display: dt_dsp_button.md
        - Image Display: dt_dsp_image.md

      - Networking:
        - What Is NetworkTables?: dt_net_basics.md
        - Connecting To The Robot: dt_net_connecting.md

      - _ROBOT_:
        - What Is This Folder? : dt_rob_about.md

        - Classes:
          - nav_field: dt_rob_nav_field.md
          - nav_path: dt_rob_nav_path.md
          - nav_robot: dt_rob_nav_robot.md
          - Vectors: dt_rob_vectors.md

    - I Want To Make A Dashboard!: dt_development.md


theme:
  name: 'windmill-dark'
  custom_dir: 'mkdocs-windmill-dark/mkdocs_windmill_dark'
